// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/stebin13/x-tentioncrew/microservice-1/pkg/api"
	"github.com/stebin13/x-tentioncrew/microservice-1/pkg/api/service"
	"github.com/stebin13/x-tentioncrew/microservice-1/pkg/config"
	"github.com/stebin13/x-tentioncrew/microservice-1/pkg/db"
	"github.com/stebin13/x-tentioncrew/microservice-1/pkg/repository"
)

// Injectors from wire.go:

func InitializeServe(c *config.Config) (*api.Server, error) {
	gormDB, err := db.Initdb(c)
	if err != nil {
		return nil, err
	}
	client, err := db.InitRedis(c)
	if err != nil {
		return nil, err
	}
	userRepo := repository.NewUserRepo(gormDB, client)
	userServiceServer := service.NewUserServer(userRepo)
	server, err := api.NewgrpcServe(c, userServiceServer)
	if err != nil {
		return nil, err
	}
	return server, nil
}
