// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/stebin13/x-tentioncrew/microservice-2/pkg/api"
	"github.com/stebin13/x-tentioncrew/microservice-2/pkg/api/service"
	"github.com/stebin13/x-tentioncrew/microservice-2/pkg/client"
	"github.com/stebin13/x-tentioncrew/microservice-2/pkg/config"
)

// Injectors from wire.go:

func InitializeServe(c *config.Config) (*api.Server, error) {
	userServiceClient, err := client.InitClient(c)
	if err != nil {
		return nil, err
	}
	userClient := client.NewUserClient(userServiceClient)
	methodServiceServer := service.NewMethodServer(userClient)
	server, err := api.NewgrpcServe(c, methodServiceServer)
	if err != nil {
		return nil, err
	}
	return server, nil
}
